import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  background: {
    backgroundColor: '#FEF7F1',
    flex: 1,
  },
  menuicon: {
    width: 35,
    height: 35,
    tintColor: '#EF8F52',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 25,
  },
  searchbar: {
    backgroundColor: '#EF8F52',
    width: '90%',
    height: 60,
    borderRadius: 20,
    flexDirection: 'row',
  },
  searchbarpos: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    margin: 15,
  },
  searchtxt: {
    fontSize: 20,
    fontWeight: 'semibold',
    color: '#ffff',
    marginLeft: 20,
  },
  searchicon: {
    width: 20,
    height: 20,
    tintColor: '#ffff',
  },
  categorybar: {
    backgroundColor: '#EF8F52',
    width: 100,
    height: 40,
    borderRadius: 15,
    margin: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  categories: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  unselectcategorybar: {
    borderColor: '#EF8F52',
    borderWidth: 2,
    width: 100,
    height: 40,
    borderRadius: 15,
    margin: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  alltxt: {
    fontWeight: 'bold',
    color: '#ffff',
    fontSize: 15,
  },
  newtxt: {
    fontWeight: 'bold',
    color: '#EF8F52',
    fontSize: 15,
  },
  product: {
    width: 180,
    height: 200,
    backgroundColor: '#EF8F52',
    borderRadius: 30,
    justifyContent: 'center',
    margin: 10,
  },
  unslproduct: {
    width: 180,
    height: 200,
    borderColor: '#EF8F52',
    borderRadius: 30,
    borderWidth: 2,
    margin: 10,
    justifyContent: 'center',
  },
  line1: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icecreams: {
    width: 120,
    height: 120,
  },
  likeicon: {
    width: 20,
    height: 20,
    tintColor: '#EF8F52',
    color: '#EF8F52',
  },
  likeback: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffff',
    width: 30,
    height: 30,
    borderRadius: 30,
    marginRight: 10,
    marginBottom: 10,
  },
  likeback2: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EF8F52',
    width: 30,
    height: 30,
    borderRadius: 30,
    marginRight: 10,
    marginBottom: 10,
  },
  likeicon2: {
    width: 20,
    height: 20,
    tintColor: '#ffff',
    color: '#EF8F52',
  },
  dots: {
    backgroundColor: '#EF8F52',
    padding: 2,
    borderRadius: 20,
    width: 15,
    height: 15,
    margin: 5,
  },
  dots1: {
    borderColor: '#EF8F52',
    padding: 2,
    borderRadius: 20,
    width: 15,
    height: 15,
    margin: 5,
    borderWidth: 2,
  },
  dotspos: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
 
  bottomspacepos: {
    justifyContent: 'flex-end',
    flex: 1,
  },
  bottominside: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  stylebottomicons: {
    width: 45,
    height: 45,
    marginHorizontal: 30,
    tintColor: '#EF8F52',
  },
  iconsme: {
    width: 45,
    height: 45,
    marginHorizontal: 30,
    borderRadius: 30,
  },
});
