import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  backgrounds: {
    backgroundColor: '#FEF7F1',
    flex: 1,
  },
  product: {
    backgroundColor: '#EF8F52',
    width: '100%',
    height: 450,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 20,
  },
  headericonstyle: {
    tintColor: '#ffff',
    width: 35,
    height: 35,
  },
  likeicon: {
    width: 20,
    height: 20,
    tintColor: '#EF8F52',
    color: '#EF8F52',
  },
  likeback: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffff',
    width: 30,
    height: 30,
    borderRadius: 30,
    marginRight: 10,
    marginBottom: 10,
  },
  icecreams: {
    width: 200,
    height: 200,
  },
  products: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 30,
  },
  basketicon: {
    height: 30,
    width: 30,
    tintColor: '#ffff',
  },
  basketback: {
    backgroundColor: '#ffff',
    borderRadius: 25,
    width: 60,
    height: 60,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    opacity: 0.6,
    marginVertical: 10,
  },
  extensions: {
    margin: 25,
  },
  pricetxt: {
    fontWeight: 'bold',
    fontSize: 30,
    color: '#ffff',
    fontFamily: 'sans-serif-light',
  },
  pricepos: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginRight: 65,
  },
  staricon: {
    width: 23,
    height: 23,
    tintColor: 'white',
    opacity: 0.4,
    margin: 3,
  },
  starpos: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: 65,
    margin: 15,
  },
  nametxt: {
    fontWeight: 'bold',
    fontSize: 35,
    fontFamily: 'sans-serif',
  },
  namepos: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 25,
  },
  namepos2: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: 45,
    marginRight: 45,
  },
  name2txt: {
    color: '#EF8F52',
    fontSize: 15,
  },
  ingredientsbar: {
    backgroundColor: 'white',
    width: 140,
    height: 100,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  orderbar: {
    backgroundColor: '#EF8F52',
    width: 140,
    height: 100,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  ingretxt: {
    color: '#EF8F52',
    fontWeight: 'bold',
    fontSize: 20,
  },
  ordertxt: {
    color: '#ffff',
    fontWeight: 'bold',
    fontSize: 20,
  },
  options: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 15,
  },
  dots: {
    backgroundColor: '#EF8F52',
    padding: 2,
    borderRadius: 20,
    width: 15,
    height: 15,
    margin: 5,
  },
  dots1: {
    borderColor: '#EF8F52',
    padding: 2,
    borderRadius: 20,
    width: 15,
    height: 15,
    margin: 5,
    borderWidth: 2,
  },
  dotspos: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  bottomspace: {
    backgroundColor: '#ffff',
    width: '100%',
    height: 80,
  },
  bottomspacepos: {
    justifyContent: 'flex-end',
    flex: 1,
  },
  bottominside: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  stylebottomicons: {
    width: 45,
    height: 45,
    marginHorizontal: 30,
    tintColor: '#EF8F52',
  },
  iconsme: {
    width: 45,
    height: 45,
    marginHorizontal: 30,
    borderRadius: 30,
  },
});
